### ISSUE TITLE
Add more export formats

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-data#11]
We need to support some of the most common formats, to avoid a significant barrier for adoption. 
We support GEOJSON / csv - expand to WFS, netCDF, etc.

**Comment by matamadio** [comment]
Data access and export pipeline to be planned in detail according to frictionless strategy.

- Data format for download and inclusion of metadata: how to fit the user needs
- Conversion from stored data: assess POSTGIS capability and performances over data size.
- Enable access as WFS (not WMS, we want usable data), need to provide easy-filtered data.
- API: what do we want it to do?

**Comment by MamadioCMCC** [comment]
Issue when trying to import geojson format in QGIS; cannot import geojson with metadata header.

This loads no problem in QGIS:
```
{
"type": "FeatureCollection",
"name": "rdl-lss-Earthquake-76",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [ ... ]
 },
```

While this, with MD added in the header, does not load:
```
{
  "contribution": {
    "model_date": "2016-01-01",
    "model_source": "AIR Worldwide",
    "notes": "This data set was produced with financial support from the European Union in the framework of the ACP-EU Natural Disaster Risk Reduction Program, managed by the Global Facility for Disaster Reduction and Recovery (GFDRR).",
    "version": "V1",
    "project": "GFDRR South West Indian Ocean Risk Assessment and Financing Initiative (SWIO-RAFI)",
    "license_code": "CC BY-SA 4.0",                                             "
    "purpose": "Quantification of site specific risk of flood, earthquakes, tropical cyclones, storm surge and tsunamis, to support improvement in the resiliency and capacity of South West Indian Ocean island states through the creation of disaster risk financing strategies.",
  },   
  "model": {
	"name": "Madagascar aggegrate losses (total EP, ADM1 level)",
  },
    "map": {
	"occupancy": "Mixed",
	"component": "Buildings",
	"loss_type": "ground-up",
	"units": "USD",
	"metric": "AAL and RPs",
  },
"type": "FeatureCollection",
"name": "rdl-lss-Earthquake-76",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [...],
```

**Comment by matamadio** [comment]
Details on geojson data curation and metadata
https://github.com/DataCurationNetwork/data-primers/blob/master/GeoJSON%20Data%20Curation%20Primer/GeoJSON-data-curation-primer.md#geojson-metadata-standards

**Comment by matamadio** [comment]
Superceeded for previous implementation.
Standard formats to be identified, conversion modules to be discussed in next implementation.
