### ISSUE TITLE
extend hazard schema - technological and biological hazards

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-data#15]
Extension of attributes and possibly data fields required to support possible extensions e.g.
Pandemic, dam burst, pipeline burst, nuclear, oil spill etc.

**Comment by stufraser1** [comment]
alignment with UNDRR 2020 hazard classification would help with this
https://www.undrr.org/publication/hazard-definition-and-classification-review

**Comment by matamadio** [comment]
Closing, discussion continues with more details on https://github.com/GFDRR/rdl-standard/issues/2
