### ISSUE TITLE
rename name mover.f_core.licence_code

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-data#17]
rename mover.f_core.licence_code to mover.f_core.license_code
(consistent with other schema)

**Comment by stufraser1** [comment]
to be done in alchemy version please @ConnectedSystems

**Comment by ConnectedSystems** [comment]
Addressed by changes to RISKi (see https://github.com/GFDRR/RISKi/commit/9d17911cbe2be6e9e14a511c340e51ba50ca3832)
