### ISSUE TITLE
Schema tables and attributes optimisation

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-data#23]
Split into individual issues.

**Comment by stufraser1** [comment]
@MamadioCMCC please edit to make this a checklist, and separate into individual issues (where not done so already) so we can discuss individually and close as completed. Add a label to reference all issues as 'Q1-2021 schema updates'?

cross reference please with this file - I have recorded some of these issues before, make sure to capture any additional from that doc:
https://docs.google.com/document/d/1G6dbuB0L7JNTCjrkC7oozMEP8hALfjADCnbEdR17-y8/edit?usp=sharing (summary)
https://docs.google.com/document/d/1crMtbgasIDGX6799nC23SRSdvb_CxkoaDOHVgNuMqVc/edit?usp=sharing (full table)
