### ISSUE TITLE
Issue with flood types definitions from SWIO-RAFI

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-data#24]
From SWIO-RAFI datasets we have:

Tropical cyclones
  Coastal Floods
  Pluvial Floods
  Wind
Non-tropical cyclones
  Pluvial floods

For both pluvial floods, that translates as:

    Tropical Cyclon (trigger) > Flood (hazard type) > Pluvial (process)
    Extra- Tropical Cyclon (trigger) > Flood (hazard type) > Pluvial (process)
    
Fitting to hazard schema, both pluvial datasets becomes FL > FPF, and the difference between them becomes not obvious; it is still included in the description, plus we can use "trigger_process_type" in the "event" table to keep this information using "TCY" and "ETC". However, both processes relates to wind speed units only, so that would not be appropriate.

**Comment by stufraser1** [comment]
Lots of studies provide a single pluvial layer, and where TC and non-TC sources both are accounted for in the pluvial hazard footprint. In my experience this is most common. We could create another FPF definition but this would mean 3 FPF codes wth same units: FPF-TC, FPF-NonTC, FP-both, and I don't think this is a helpful addition - more confusing than not. 
I think the trigger process is an interesting solution. If you think about EQ and tsunami, the EQ as trigger has different units than the tsunami footprint, so the same case often applies.

**Comment by matamadio** [comment]
Agreed; trigger to be used for this particular cases.
