### ISSUE TITLE
Improve docker build pattern

### ISSUE THREAD

**Issue by jeanpommier** [GFDRR/rdl-data#25]
Hi,
It took me some time to understand how the docker image is built : the Dockerfile uses a dump.sql file, that is produced beforehand by the Makefile start command. This doesn't seem very portable for me. The current workflow works in this configuration, but would not be straightforward for, for instance, building and pushing a docker image, without running it first on the local computer. 

I don't see any strong reason to proceed this way. I may have missed something, but I believe you could skip the aggregation step and just copy all the sql/*.sql files into /docker-entrypoint-initdb.d/ and then let postgres image load the scripts, as documented on https://hub.docker.com/_/postgres
It would just mean renaming the files (the digits prefix) so that create-users.sql runs first.

Then the Makefile would be very trivial, maybe unnecessary even (limited to docker-compose up / down)

**Comment by matamadio** [comment]
Thanks Jean, with the migration of RDL to new AWS server we are looking to optimise the overall infrastructure of the platform. This includes simplify the whole docking creation, possibly getting rid of terraform if it is not strictly necessary to our needs.
What you think?

**Comment by matamadio** [comment]
Related to old (superceeded) infra: closing.
