### ISSUE TITLE
Edit the ged4all.occupancy table in E schema.

### ISSUE THREAD

**Issue by matamadio** [GFDRR/rdl-data#28]
This attribute basically applies only to population, residing in a location or just moving/working through a location.

Required | Field Name | Type | Reference
-- | -- | -- | --
  | * | id | INT | Unique number ID
  | * | asset_id | INT | Unique number ID of the asset
  | * | period | VARCHAR | Occupancy type (night/day)
  | * | occupants | FLOAT | Number of occupants

It may be confused with "occupancy_enum" common type (see #26 ).
I'd put it as optional instead of required since many occupancy types do not expect to have population data. May need more thinking.

**Comment by matamadio** [comment]
Suggest to call it "pop_occupancy" or "occupancy_period", both period and occupants to be optional fields.

**Comment by stufraser1** [comment]
Agreed on renaming, especially as we work more with DRF/insurance data occupancy is the term most commonly used to refer to building usage. Suggests to call table 'occupants' with the field renamed 'num_occupants' to be more specific
Agree on making it optional.
