### ISSUE TITLE
Consider using SPDX ids for licences

### ISSUE THREAD

**Issue by ldodds** [GFDRR/rdl-data#37]
The  cf_common.license tables in the database includes a list of open data licences. These are currently using custom codes based on those using by OKF in [the list of conformant open data licences](https://opendefinition.org/licenses/) which in turn use [the SPDX licence codes](https://spdx.org/licenses/).

Suggest using the SPDX codes directly, rather than custom codes. 

In addition to avoiding the need to keep adding new codes using the SPDX codes directly makes it easier to track which version of a licence is being used. Sometimes there are important differences between licences. For example the 4.0 versions of the CC-BY (and other) licences covers data, database rights, etc whereas previous versions do not.

The OKF list is still the definitive list of open data licences that have been through the approval process, but there are some conformant open data licences that have not, simply because they haven't been submitted. The SPDX list includes a mixture of data and software licences. If the intention is to recommend a set of open data licences, then the OKF list is the right one to use. But in terms of a standard set of licence identifiers, the SPDX list is more inclusive.

**Comment by stufraser1** [comment]
Good recommendation - lets use the OKF list with SPDX codes, instead of the custom ones used now.

**Comment by matamadio** [comment]
Ok then, I'm goin to include the recommended format codes from the first link: https://opendefinition.org/licenses/

Creative Commons CCZero (CC0-1.0)
Open Data Commons Public Domain Dedication and Licence (PDDL-1.0)
Creative Commons Attribution 4.0 (CC-BY-4.0)
Open Data Commons Attribution License (ODC-By-1.0)
Creative Commons Attribution Share-Alike 4.0 (CC-BY-SA-4.0)
Open Data Commons Open Database License (ODbL-1.0)

**Comment by matamadio** [comment]
Do we want logos as well?
Example:
![immagine](https://licensebuttons.net/l/by/3.0/88x31.png)
![immagine](https://licensebuttons.net/l/by-sa/3.0/88x31.png)

**Comment by stufraser1** [comment]
logos not necessary

**Comment by matamadio** [comment]
Licenses implemented in JKAN website (see licenses in https://gfdrr.github.io/rdl-jkan/admin/)
Next, show short name as anchor to url (see jkan issue).
Closing
