### ISSUE TITLE
Consistent country reference

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-data#4]
MOVER, using ("PRT;FRA;ITA;MAR;BGR", "TZA") is inconsistent with the other schema in data content and meaning (represents the country for which the curves are developed - data form that country); To make consistent, propose to add a new field for country name (and possibly country ISO to other schema). Different info labelling could account for difference in meaning This shows that values could be a list (covering more than one country).

**Comment by stufraser1** [comment]
see also https://github.com/GFDRR/rdl-data/issues/18

**Comment by matamadio** [comment]
Instead of adding the field to all the 4 schemas, could that be just part of the "common" attributes schema?

**Comment by stufraser1** [comment]
The list of country codes, names should be - as for hazard codes - to
ensure each schema uses same values.
Each schema would need to include though, with country code as value.

**Comment by matamadio** [comment]
Proposal using common table applied to each schema:

Table name | Required | Field name | Type | Description
-- | -- | -- | -- | --
cf_common.isocover | * | code | ENUM | Alpha-3 ISO 3166 country code(s), separated by comma.


TYPES

Country | isocover_enum
-- | --
Afghanistan | AFG
Albania | ALB
...

**Comment by stufraser1** [comment]
agree - but ensure to use WB official country names

**Comment by matamadio** [comment]
Table added to documentation. common schema: https://gfdrr.github.io/rdl-doc/common.html#table-cf_commoniso

It has to be referenced in each schema and added to SQL, see #27 @ConnectedSystems

**Comment by ConnectedSystems** [comment]
Added in, but could not consistently enforce foreign key relationships.

Contribution tables for

* Loss
* Hazard
* Exposure

do not currently have a `country_iso` field.

Vulnerability/Mover does.

EDIT: I've added a `country_iso` field into the above 3, @MamadioCMCC could you update the documentation to reflect this?

**Comment by matamadio** [comment]
Yes, I will thanks. Btw, we should enable one or more country to be listed (e.g. ITA; FRA; SPA) for regional datasets
