### ISSUE TITLE
record data as to be published or not

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-data#5]
Present situation: a list of dataset IDs in json file limits the files shown on the website.
Could this be improved by adding a field in the database - ‘published’ - that flags whether the dataset should be published or not?

**Comment by matamadio** [comment]
That should be added in the contribution table as boolean.

**Comment by matamadio** [comment]
Easy to implement if agreed - good to have a flag to fast hide datasets if needed.
@ConnectedSystems

**Comment by ConnectedSystems** [comment]
Added `published` field to `Contribution` and `f_core` tables.

Just to note, this is more an implementation detail more than a concern of the schema (i.e., the "standard").
I think it warrants, at most, a note in the documentation saying adopters could add this in, but I don't think it is necessary to reflect it in the documentation (i.e., in the tables, figures, etc.).

**Comment by ConnectedSystems** [comment]
Addressed by changes to RISKi (see https://github.com/GFDRR/RISKi/commit/9d17911cbe2be6e9e14a511c340e51ba50ca3832)
