### ISSUE TITLE
Raster support

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-data#6]
Explore POSTGIS Raster storage function or conversion to raster in pipeline - for hazard in particular, but also gridded aggregate exposure data

**Comment by matamadio** [comment]
Linked to https://github.com/GFDRR/rdl-infra/issues/44

**Comment by matamadio** [comment]
Each schema (H and E for sure) should have the capability to ingest both vector and raster formats.

**Comment by matamadio** [comment]
We found POSTGIS is unlikely a good option for raster storage, in favour of traditional file-based storage.
Ultimately, the out-DB approach should aim to integrate all three key formats (vector, raster and table) within any component of the schema, avoiding as possible to convert one format into the other (unless this improves the fruibility of the dataset).

**Comment by matamadio** [comment]
Old-superceeded discussion.
