### ISSUE TITLE
Hazard - store stochastic event set

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/rdl-data#9]
Extend function of hazard schema to include storage of stochastic event set tables

**Comment by matamadio** [comment]
Well the schema has the option for probabilistic, and we can store multiple footprint sets for each event stochastic realisation.
Or I didn't understand what you mean.

**Comment by stufraser1** [comment]
This is not about storing the footprint for each event in an event set but the table of events.
E.g. event ID, frequency.
But it true, if we wanted to store the losses, it is covered in proposed change to loss schema (#10), and if we want to store event information beyond ID and frequency (to be useful) it should be stored in footprint set.
Closing
